openapi: 3.0.3
info:
  title: Car Reservation Service v1
  description: |-
    API for Car Reservation Service
  termsOfService: http://swagger.io/terms/
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
tags:
  - name: CarReservation
    description: Platform for car sharing
paths:
  /api/v1/reservation-request:
    post:
      tags:
        - Reservation
      description: Register a new reservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiReservationRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservationRequestResponse'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /api/v1/reservation-confirmation:
    post:
      tags:
        - Reservation
      description: Confirm or Decline a previously requested reservation
      summary: Submit reservation confirmation
      operationId: apiV1ReservationConfirmationPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiReservationConfirmation'
      responses:
        '200':
          description: Successful operation
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/reservation/{day}:
    get:
      tags:
        - Reservation
      description: Get an overview of all Reservations for a single day
      parameters:
        - in: path
          name: day
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservationOverview'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /api/v1/reservation/{reservationId}/bill:
    get:
      tags:
        - Reservation
      description: Get the billing details for a reservation
      parameters:
        - in: path
          name: reservationId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservation'
        '500':
          description: Internal Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  schemas:
    ApiReservationOverview:
      type: object
      properties:
        day:
          type: string
          format: date
        reservations:
          type: array
          items:
            $ref: '#/components/schemas/ApiReservation'
    ApiReservation:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        email:
          type: string
        carId:
          type: integer
        carType:
          type: string
        totalCost:
          type: number
        totalDays:
          type: integer
        ownerEmail:
          type: string
    ApiReservationRequest:
      type: object
      properties:
        userId:
          type: integer
        carId:
          type: integer
        preferredDay:
          type: string
          format: date
          example: '2023-09-21'
        totalDays:
          type: integer
    ApiReservationRequestResponse:
      type: object
      properties:
        reservationRequestNumber:
          type: string
          example: "23-11-5678"
    ApiReservationConfirmation:
      type: object
      properties:
        reservationRequestNumber:
          type: string
          example: "23-11-5678"
        acceptProposedReservation:
          type: boolean
    ApiError:
      type: object
      properties:
        code:
          type: string
          description: 'Functional code specifying the error'
          example: '2300'
        message:
          type: string
          description: 'Brief explanation about the error, for more information consult the Doctor Service team'
    ReservationFinalizedEvent:
      type: object
      properties:
        reservationRequestNumber:
          type: string
          example: "23-11-5678"
        day:
          type: string
          format: date
        userId:
          type: integer
        ownerId:
          type: integer
        carId:
          type: integer
        accepted:
          type: boolean